# Generated by Django 5.1.2 on 2024-10-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField()),
            ],
        ),
    ]
