# Generated by Django 5.1.2 on 2024-10-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='PythonMembers',
        ),
    ]
