# Generated by Django 5.1.2 on 2024-10-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pythonmember_rename_pythonmembers_ccharpmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccharpmember',
            options={'verbose_name': 'C# Member', 'verbose_name_plural': 'C# Members'},
        ),
        migrations.AddField(
            model_name='ccharpmember',
            name='collage',
            field=models.CharField(default='CIS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pythonmember',
            name='collage',
            field=models.CharField(default='CIS', max_length=100),
            preserve_default=False,
        ),
    ]
