# Generated by Django 5.1.2 on 2024-10-14 18:33

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ccharpmember_options_ccharpmember_collage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccharpmember',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='pythonmember',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ccharpmember',
            name='user_code',
            field=models.CharField(default='C2204765', max_length=9, primary_key=True, serialize=False, validators=[main.validators.validate_user_code]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pythonmember',
            name='user_code',
            field=models.CharField(default='C2204765', max_length=9, primary_key=True, serialize=False, validators=[main.validators.validate_user_code]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ccharpmember',
            name='collage',
            field=models.CharField(choices=[('Computer information systems', 'Cis'), ('Mangement information systems', 'Mis'), ('Arts', 'Art'), ('Engineering', 'Eng')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pythonmember',
            name='collage',
            field=models.CharField(choices=[('Computer information systems', 'Cis'), ('Mangement information systems', 'Mis'), ('Arts', 'Art'), ('Engineering', 'Eng')], max_length=100),
        ),
    ]
