# Generated by Django 5.1.2 on 2024-11-08 12:53

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ccharpmember_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicDesginMember',
            fields=[
                ('user_code', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[main.validators.validate_user_code])),
                ('username', models.CharField(max_length=100)),
                ('collage', models.CharField(choices=[('Computer information systems', 'Cis'), ('Mangement information systems', 'Mis'), ('Arts', 'Art'), ('Engineering', 'Eng')], max_length=100)),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Graphic Desgin Member',
                'verbose_name_plural': 'Graphic Desgin Members',
            },
        ),
    ]
