# Generated by Django 5.1.2 on 2024-11-08 13:18

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_graphicdesginmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccharpmember',
            name='user_code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[main.validators.validate_csharp_code]),
        ),
        migrations.AlterField(
            model_name='graphicdesginmember',
            name='user_code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[main.validators.validate_graphic_desgin_code]),
        ),
        migrations.AlterField(
            model_name='pythonmember',
            name='user_code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[main.validators.validate_py_code]),
        ),
    ]
