# Generated by Django 5.1.2 on 2024-11-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ccharpmember_user_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccharpmember',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='graphicdesginmember',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='pythonmember',
            name='collage',
        ),
    ]
